### ISSUE TITLE
Can the library use `chrono::DateTime` instead of `SystemTime` everywhere Alpaca is giving a timestamp?

### ISSUE THREAD

**Issue by zjijz** [d-e-s-o/apca#13]
How would you feel about making this change? `chrono` provides a method to parse RFC3339 timestamps as well: https://docs.rs/chrono/0.4.19/chrono/struct.DateTime.html#method.parse_from_rfc3339.

I would be willing to give it a shot to implement as well.

**Comment by d-e-s-o** [comment]
Yeah, I think we can do that. I'd be happy to merge if done properly. We should get rid of the `time-util` dependency then.

**Comment by zjijz** [comment]
Ah, I hadn't noticed you had a library that dealt with timezones from `SystemTime`. I was using `chrono` already and just started wondering how I would try to deal with the `SystemTime`s and the type-checked `DateTime`. I'll see if it's relatively easy to change. Would you want it behind a feature flag?

**Comment by d-e-s-o** [comment]
I don't think it can be done behind a feature flag (unless I am misunderstanding what you are suggesting). I'd suggest just introducing a `time` module in `apca`'s root and putting everything needed in there. Just a random thought.

**Comment by zjijz** [comment]
Just that there could be a feature flag that controls putting `SystemTime` or `DateTime` into a struct. I think it's a breaking change otherwise.

**Comment by d-e-s-o** [comment]
Ah. Nah, let's just do the switch. I'll have to bump the minor version anyway.

**Comment by d-e-s-o** [comment]
https://github.com/d-e-s-o/apca/pull/14 got merged. Thanks for bringing this up and driving it to the finish line!
