### ISSUE TITLE
Add support for notional orders

### ISSUE THREAD

**Issue by behos** [d-e-s-o/apca#17]
Hi!

Great work with the client SDK! I started using it and tracking some changes in a fork to add some features that I needed.

One of them is adding support for notional orders. This affects the types of several different API objects, so I'd like to hear your opinion on how to support this properly (I made some hacky changes to get things working but haven't written tests yet).

https://github.com/d-e-s-o/apca/pull/16

What do you think?

**Comment by d-e-s-o** [comment]
Thanks for the proposal. I took a quick look. Will comment on the pull request.

**Comment by d-e-s-o** [comment]
Pull request has been merged. Forgot to close this issue.
