### ISSUE TITLE
How to go about streaming stock quotes?

### ISSUE THREAD

**Issue by elertan** [d-e-s-o/apca#2]
Using `alpaca-trade-api-js` it is possible to subscribe to stock quotes using tickers/alpaca ids.
Does this crate support that feature?

**Comment by d-e-s-o** [comment]
You can use [`polyio`](https://github.com/d-e-s-o/polyio) (or [`polycli`](https://github.com/d-e-s-o/polycli)) for streaming stock quotes. I am not familiar with `alpaca-trade-api-js`.

**Comment by elertan** [comment]
Thanks for the quick repsonse @d-e-s-o , that seems to do actually what I want.
The library I mentioned is a first party library from alpaca for NodeJS.

**Comment by mkeedlinger** [comment]
Please correct me if I'm wrong, but Alpaca no longer comes with polygon access and they now [offer their own API](https://alpaca.markets/docs/api-documentation/api-v2/market-data/alpaca-data-api-v2/real-time/) for streamed market data.

@d-e-s-o Would supporting that API be in scope for this project? If it is, I could create an issue for it and look into making a PR.

**Comment by d-e-s-o** [comment]
> @d-e-s-o Would supporting that API be in scope for this project? If it is, I could create an issue for it and look into making a PR.

Yeah, I think it's within the scope of the project. There has been some discussion (including a prototype) over in https://github.com/d-e-s-o/apca/issues/12. I'd be happy to merge a pull request if it fits well into the crate. I believe the core logic from `polyio` could be used as well.
