### ISSUE TITLE
Downloading stock price data freezes

### ISSUE THREAD

**Issue by Gadersd** [d-e-s-o/apca#23]
I tried to download stock price data via the code below.

```
let request = BarReq {
              symbol: stock_symbol,
              limit: None,
              start: *start_time,
              end: *end_time,
              page_token: None,
              timeframe: timeframe,
              adjustment: Some(Adjustment::All)
            };

let bars = block_on(self.client.issue::<bars::Get>(&request)).unwrap();
```

However, after downloading the data for some of the assets, the block_on code freezes and never unwraps. I assume this is because I am exceeding Alpaca's request limit, but the code should either unwrap into an error or wait until Alpaca will receive further requests.

**Comment by Gadersd** [comment]
Here is a complete code example that illustrates the issue.
```
use chrono::{NaiveTime, Duration, Date, DateTime, Utc};

use futures::executor::block_on;

use apca::api::v2::order;
use apca::data::v2::bars::{self, *};
use apca::api::v2::account;
use apca::api::v2::position;
use apca::api::v2::clock;
use apca::api::v2::asset::{Symbol, Status, Class, Asset};
use apca::api::v2::assets;
use apca::ApiInfo;
use apca::Client;

#[tokio::main]
async fn main() {
    let key_id = "your key";
    let secret_key = "your secret key";

    let api_info = ApiInfo::from_parts("https://paper-api.alpaca.markets", key_id, secret_key).unwrap();
    let client = Client::new(api_info);

    let request = assets::AssetsReq {
        status: Status::Active,
        class: Class::UsEquity,
    };

    // download the asset information
    let assets = block_on( client.issue::<assets::Get>(&request) ).unwrap();

    let current_time = Utc::now();

    // start a few years from now
    let start_time = current_time.checked_sub_signed(Duration::days(365 * 4)).unwrap();

    // end on the previous day
    let end_time = current_time.checked_sub_signed(Duration::days(1)).unwrap();

    let asset_bars: Vec<(String, Vec<Bar>)> = assets.iter().map(|asset| {
        println!("Downloading bars data for {}", asset.symbol);

        let request = BarReq {
            symbol: asset.symbol.clone(),
            limit: None,
            start: start_time,
            end: end_time,
            page_token: None,
            timeframe: apca::data::v2::bars::TimeFrame::OneDay,
            adjustment: Some(Adjustment::All)
          };

          // get the bars for this stock symbol
          (asset.symbol.clone(), block_on(client.issue::<bars::Get>(&request)).unwrap().bars)
    }).collect();

    println!("All done!");
}
```

The downloading will continue for a while but eventually freezes on an asset. The asset that it freezes on varies from run to run for me.

**Comment by d-e-s-o** [comment]
You probably shouldn't be nesting executors like this. You are already running in a `tokio` runtime and then effectively doing a blocking call in there with `block_on`. While I am not sure why that would lead to a dead lock, it's certainly not how it's intended to be used.

**Comment by d-e-s-o** [comment]
Can you rewrite the code with `await`s instead of `block_on` and see if it reproduces?

**Comment by Gadersd** [comment]
Replacing `block_on` with corresponding `await`s does indeed work. I am confused why `block_on` induces dead locks. Is this expected or might this be a bug in apca or elsewhere?

**Comment by d-e-s-o** [comment]
Glad it's working now. It has nothing to do with `apca`; as I said it's not expected by any runtime that executors be nested. That's by design of how `async`/`await` work in Rust from what I understand.

**Comment by d-e-s-o** [comment]
Btw., here is an upstream issue for such a hang: https://github.com/tokio-rs/tokio/issues/2376
