### ISSUE TITLE
Quotes streaming

### ISSUE THREAD

**Issue by stalexxx** [d-e-s-o/apca#24]
I wish to be able to subscribe on quot stream in addition to bars, like [example](https://alpaca.markets/docs/api-documentation/api-v2/market-data/alpaca-data-api-v2/real-time/#:~:text=key%22%3A%22PK******************%22%2C%22secret%22%3A%22***********************************%22%7D-,Subscribe,-%23) said

**Comment by d-e-s-o** [comment]
Changes got merged and will be available in the next release. Thanks for your help!

**Comment by stalexxx** [comment]
cool! my first contribution into rust code
