### ISSUE TITLE
No crypto support

### ISSUE THREAD

**Issue by Gadersd** [d-e-s-o/apca#26]
Alpaca recently added support for cryptocurrency trading, but apca seems to not be able to handle the new "crypto" asset class. When I attempted to request my positions I received the error: Conversion(Json(Error("unknown variant 'crypto', expected 'us_equity'"))).

**Comment by Gadersd** [comment]
The code that causes the error is 
`let positions = client.issue::<positions::Get>( &() ).await.unwrap();`

**Comment by d-e-s-o** [comment]
`crypto` isn't currently supported, and not exactly planned either (though I may play around with it at some point). That being said, we should most certainly be handling this a bit more gracefully.

**Comment by Gadersd** [comment]
Can you give an estimate as to when this may be resolved? As it stands apca is unusable for me since I have invested in cryptocurrencies with Alpaca. Otherwise, do you know of any rust Alpaca crates that do or plan on handling this?

**Comment by d-e-s-o** [comment]
I have a bunch of changes piled up that I want to push out; there is a chance it may happen this weekend. No idea about other crates, though, sorry.

**Comment by d-e-s-o** [comment]
Can you try with https://github.com/d-e-s-o/apca/commit/d80e1eb5c28c29e80191dd0c32320876ab52e8d4, please?

**Comment by Gadersd** [comment]
The positions request no longer throws an error. Thank you for the swift fix.
