### ISSUE TITLE
Standardize DateTime creation for tests

### ISSUE THREAD

**Issue by husafan** [d-e-s-o/apca#29]
Currently, there are [different](https://github.com/d-e-s-o/apca/blob/7bd3027cc52c0171488f49b27dcfe0d116ada1e8/src/data/v2/bars.rs#L273) [ways](https://github.com/d-e-s-o/apca/blob/7bd3027cc52c0171488f49b27dcfe0d116ada1e8/src/data/v2/bars.rs#L431) to create UTC DateTime objects in tests.

Standardize around a single way.

**Comment by d-e-s-o** [comment]
Thanks for picking this up! This should be a strictly syntactical change. My preference is for using `DateTime::from_str("2022-02-01T00:00:00Z").unwrap()` style datetime specification throughout all the crate's tests.
