### ISSUE TITLE
Create a mock test client?

### ISSUE THREAD

**Issue by husafan** [d-e-s-o/apca#30]
If I am reading some of the data tests correctly, it looks like the tests are pulling API keys from the environment and talking to the API? For testing, would it not be better to mock the client responses to remove environment and connectivity dependencies?

**Comment by d-e-s-o** [comment]
> If I am reading some of the data tests correctly, it looks like the tests are pulling API keys from the environment and talking to the API?

You are correct.

> For testing, would it not be better to mock the client responses to remove environment and connectivity dependencies?

Well, I argue not really. Alpaca has repeatedly broken API contracts. Without live tests we'd be flying blind as we'd still be testing against stale responses.
Also, you'd never get exposed to the various idiosyncracies of the API this way. E.g., different responses at different times of the day (which in turn change over time). It's very easy to create a paper trading account (I have at least three) and there is significant value in having it for testing. There may still be differences to live trading, but that's entirely on the Alpaca side of things.
That being said, we do have some mock tests, for testing serialization/deserialization of reference responses, but these are mostly for unit test style verification of chosen implementation details. I also have (unpublished) changes that emulate an entire broker locally, which would forego actual internet traffic, but it's not a full replacement for the obvious reason that we'd now be again testing against our own implementation/mocked behavior etc.

**Comment by husafan** [comment]
Ok - makes sense. Thanks for expanding.
