### ISSUE TITLE
Investigate response headers in relation to rate limiting

### ISSUE THREAD

**Issue by husafan** [d-e-s-o/apca#33]
https://alpaca.markets/docs/api-references/trading-api/#rate-limit

Do rate-limited requests return a [`Retry-After`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) response header? If so, it should be exposed and utilized.

**Comment by d-e-s-o** [comment]
For this task, there is not much to add to what my notes said. Try hitting the rate limit and then see if the HTTP header is provided by Alpaca. If it is, we need to think about how to expose it. Unfortunately, I am not sure how easy it will be to expose the value (should there be one) given our current infrastructure. But we can think about that once we know we need to plumb it through.

**Comment by husafan** [comment]
I created a postman.co workspace with an API POST call to /v2/order to place a buy order for a penny stock. I then ran the workspace 500 times with no delay between calls. As stated in the API, I eventually started receiving 429 response codes.

Response headers for a sample 200:

```
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Apca-Api-Key-Id, Apca-Api-Secret-Key, Authorization
Access-Control-Allow-Methods: GET, OPTIONS, PUT, DELETE, POST, PATCH
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 1728000
Connection: keep-alive
Content-Length: 771
Content-Type: application/json; charset=UTF-8
Date: Sun, 01 May 2022 14:05:56 GMT
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
X-Ratelimit-Limit: 200
X-Ratelimit-Remaining: 197
X-Ratelimit-Reset: 1651413956
```

Response headers for a sample 429:

```
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Apca-Api-Key-Id, Apca-Api-Secret-Key, Authorization
Access-Control-Allow-Methods: GET, OPTIONS, PUT, DELETE, POST, PATCH
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 1728000
Connection: keep-alive
Content-Length: 49
Content-Type: application/json; charset=UTF-8
Date: Sun, 01 May 2022 14:06:51 GMT
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
X-Ratelimit-Limit: 200
X-Ratelimit-Remaining: 0
X-Ratelimit-Reset: 1651414071
```

While there is no [`Retry-After`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After), it looks like `X-Ratelimit-Reset` contains a valid unix epoch timestamp. For example, in the above 429, the returned `Date` value is `Sun, 01 May 2022 14:06:51 GMT`. The `X-Ratelimit-Reset` converts to `Sunday, May 1, 2022 14:07:51 PM`, which is one minute after the response `Date`. This matches up with the documentation rate limiting per minute. 

It is also worth noting, as seen in the following screen shot of the postman run, that the 429's and 200's are interspersed once the 429's start occurring:
![Screen Shot 2022-05-01 at 9 14 59 AM](https://user-images.githubusercontent.com/208079/166152412-a94306fe-6df8-4f3c-80c5-93f8d2fcf0e3.png)

This would seem to indicate that, per API key, each request incurs a 1 minute counter that decays at the time indicated by `X-Ratelimit-Reset`. Whenever a request is made, if the counter is over 200, a 429 is returned. If desired, a similar counter could be maintained in the client code and used to emulate `Retry-After` functionality. Thoughts?

**Comment by d-e-s-o** [comment]
Awesome, thanks for the detailed analysis! Just to be sure I understand: the picture doesn't have time stamps in it so I am not sure when we got the 200 returns again. But it sounds as if it's basically a sliding window of `x request over 1 minute` that is allowed. And so we'd be able to do `x/60` requests again after waiting a second after seeing a 429, correct? `X-Ratelimit-Reset` would indicate when we have a full `x` requests available again and `X-Ratelimit-Remaining + 1` in our initial request would equate to `x`.

Honestly, if that's the case I'd probably lean on the side of simplicity and don't do much at all, for the simple reason that the next request would not be blocked for a minute or so but just for a really short amount. It's common sense to not *immediately* fire the request again or at least have some kind of back-off after the next rejection. So I'd just outline the behavior in the documentation that we have surrounding rate limits (not necessarily stating `x`, as it may change and is not documented by Alpaca either), but that's it. `X-Ratelimit-Reset` and `X-Ratelimit-Remaining` both don't really have a whole lot significance to clients then. It does not matter much if ten or twenty requests are allowed for anything but hypothetical use cases. Let me know if you feel differently.

**Comment by husafan** [comment]
Yes - your understanding matches mine.

And I agree that I don't think there's much to be gained by building out the mechanics of this for the common case. As you mention, the caveat is that the granularity of the sliding window does seem to be seconds, vs. milliseconds, as indicated by the units of `X-Ratelimit-Reset`. So any sort of back-off mechanism gains nothing by trying again in under a second. If a client plans on firing off 200 requests in under a second, then a specialized component to track `X-Ratelimit-Reset` and batch requests at appropriate times probably makes sense to keep from spamming the endpoints. But I don't know that this needs to be part of this library?

**Comment by d-e-s-o** [comment]
> But I don't know that this needs to be part of this library?

It probably doesn't. I was mostly worried about some kind of cliff based rate limit, where a client would have to wait up to a minute to be able to do anything again. I'd just adjust the documentation a bit and call this task done. I am fine with alluding to a one second back-off or even mentioning the 200 request limit -- it's not the end of the world if these limits go a bit out of date and it may save some users the time to investigate on their own.

**Comment by husafan** [comment]
Sounds good - marking this as resolved.
