### ISSUE TITLE
Add support for gzip response data

### ISSUE THREAD

**Issue by husafan** [d-e-s-o/apca#34]
https://github.com/alpacahq/user-docs/commit/9502318785eacf2176285f210ef4bcc172b6a3e4

**Comment by husafan** [comment]
As seen in the below postman screenshot, including an `Accept-Encoding: gzip` does appear to return gzip'd data.

<img width="1243" alt="Screen Shot 2022-05-01 at 1 41 42 PM" src="https://user-images.githubusercontent.com/208079/166162065-936d0506-473e-4be8-af2d-71fff674ba09.png">

**Comment by d-e-s-o** [comment]
Thanks! That makes sense. I think we would need to do two things then:
1) we need to set this header in the request. I think that can be done generically for all requests being made; the API should decide when it would not return `gzip`ed data for whatever reason. So from a quick look that would likely go somewhere here: https://github.com/d-e-s-o/apca/blob/9954c9ffd2f46f79b77de061de44852ffe8ce993/src/client.rs#L124
2) we need to decode `gzip`ed data, if the `Content-Encoding` says it's compressed with that. I think that would likely plug in here somewhere: https://github.com/d-e-s-o/apca/blob/9954c9ffd2f46f79b77de061de44852ffe8ce993/src/client.rs#L177

We will probably need to find a suitable compression crate first. I checked `reqwest` and it seems to use `async-compression` (which supports more than just `gzip`, but can be configured either way). I think it's probably our best bet as well, as it seems to integrate properly with the `async` eco-system (I've used it elsewhere and things seemed fine).

Perhaps it would make sense to feature gate this functionality if that can be done nicely. I'd think that by default the feature can be on.

**Comment by husafan** [comment]
Sounds good. The gzip decoding can be triggered based on whether or not the response contains the standard `Content-Encoding` header. So it should be safe to check this in. I can make `Accept-Encoding: gzip` flag-guarded to start with. Assuming no issues, the flag can eventually be deprecated in favor of this being the default.

**Comment by d-e-s-o** [comment]
Yeah, the feature is only really to have the option to compile without `gzip` support and all the crates that we'd depend on additionally. I am less worried about it breaking anything, to be honest, as long as the tests pass we should be good.

**Comment by husafan** [comment]
Ah, I see. [It looks like a feature](https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.gzip) in reqwest as well, and when the feature is enabled, gzip encoding is automatically enabled as well. This should be nice and clean.

**Comment by d-e-s-o** [comment]
Yep, exactly. Though we probably won't need runtime configurability at the client level -- just check if the Rust feature is enabled.

Also, now that I read it, we probably don't need to compress the request body, only the response body. I can't recall any requests that have a large body and it probably just adds complexity for no real gain.

**Comment by husafan** [comment]
Given the objections raised on the [original pull request](https://github.com/d-e-s-o/apca/pull/35) I see two main paths forward:

1. Use [tokio gzip decompression](https://github.com/seanmonstar/reqwest/blob/master/src/async_impl/decoder.rs#L7). It supports async out of the box, but comes with the tokio lock-in.
2. Use the [flate2 decoder](https://docs.rs/flate2/latest/flate2/read/struct.GzDecoder.html). I see [questions](https://github.com/rust-lang/flate2-rs/issues/35) [on](https://stackoverflow.com/questions/40294929/read-gzip-response-with-hyper-and-flate2) the net about this, so others must be doing it. But I am not sure how this would play with async? (I am 2 months new to Rust)

Thoughts?

**Comment by d-e-s-o** [comment]
My feeling is that 1) is our best bet: using `async_compression`. While I ideally we'd have nothing but an optional `gzip` or `deflate` (or whatever decompression crate there is) dependency, last I checked rarely do any of these come with async integration (what you also outline as a problem for 2)). The way I understand it, `async_compression` is basically a one stop shop adding async support to a bunch of common compression crates. It already differentiates between different versions of Tokio, so at least it acknowledges the existence of different runtimes. Ideally it would not be specific to one, but we have to live with what is available (and having the feature optional means it's not a hard dependency at least). Given that we can select specifically what compression support we want at build time, I think it represents the best compromise.

**Comment by husafan** [comment]
Fixed by https://github.com/d-e-s-o/apca/commit/c684db3a62e826c6428fb793dd6e53f7e44de38a
