### ISSUE TITLE
Calendar date/time.

### ISSUE THREAD

**Issue by All8Up** [d-e-s-o/apca#47]
Given that all (most?) of the other date times are represented in UTC, does it make sense for calendar to represent the day/open/close in local (or is it exchange?) timezone?  This led me on a merry chase trying to figure out why clock and calendar were not working together to find the "next" valid trading day, i.e. they are in different timezones and it was going wacked before I started dumping the data and noticed it......

**Comment by d-e-s-o** [comment]
I share your pain and I believe that ultimately it's up to Alpaca to provide timezone information. Currently their calendar API endpoint returns something along the lines of `"date":"2020-04-06","open":"09:30","close":"16:00"`, i.e., without *any* indication what time zone this stuff is relative to. Heck, not even [the immediate documentation of the very endpoint](https://github.com/alpacahq/alpaca-docs/blob/742a3191c9ffafd84d88ce47a156327b6d1b955b/data/webapi/endpoints/calendar.yaml) looses any word on that. Compare that to the [clock return object](https://github.com/alpacahq/alpaca-docs/blob/742a3191c9ffafd84d88ce47a156327b6d1b955b/data/webapi/entities/clock.yaml) that has the proper time zone information readily available.

I can't think of any excuse for this sloppiness and, to put it bluntly, I have very little interest in papering over their shitty APIs on my end, by making assumptions about what is being reported that are not properly dumented, as that removes any incentive for them to clean things up. So I'd encourage you to bring it up with them.

**Comment by All8Up** [comment]
Sensible.  Guess I'll go file a ticket with them.  This led me on a merry chase for a little while as I was used to everything else that I could just slam to Utc and ignore timezones.  I really really despise working with timezones in general, such a fiddly annoying bunch of nonsense...
