### ISSUE TITLE
example of streaming data with handlers

### ISSUE THREAD

**Issue by jaredmcqueen** [d-e-s-o/apca#59]
I'm trying to adapt [stream-realtime-data.rs](https://github.com/d-e-s-o/apca/blob/8a71eb37f7bf1f92691044a83044be0ddb7cb129/examples/stream-realtime-data.rs) to use specific handlers for the different types of `Data`.

I'm pretty sure this isn't idiomatic rust, but I can't figure out how to do it with `matches` arms.

```rust
let () = stream
    // Stop after receiving and printing 50 updates.
    // .take(50)
    .map_err(Error::WebSocket)
    .try_for_each(|result| async {
        result
            .map(|data| {
                if data.is_bar() {
                    // use a bar handler
                    println!("got bar {:?}", data);
                } else if data.is_quote() {
                    // use a quote handler
                    println!("got quote {:?}", data);
                } else if data.is_trade() {
                    // use a trade handler
                    println!("got trade {:?}", data);
                } else {
                    // use an "other" handler
                    println!("got other {:?}", data);
                };
            })
            .map_err(Error::Json)
    })
    .await
    .unwrap();
```
I'm coming from [Alpaca's Go client](https://github.com/alpacahq/alpaca-trade-api-go/blob/master/examples/marketdata/marketdata.go) and am learning Rust in the process.

Would it be possible to update the example to make it a little more clearer?  I can submit a PR once I figure it out, as well as populate a few more beginner friendly examples like the ones listed in [Alpaca's Go Repo](https://github.com/alpacahq/alpaca-trade-api-go/tree/master/examples).

Also, I know this isn't an issue - perhaps consider opening up the "discussions" area of this github repo.  Thanks for your time and such a great library, I hope to use it extensively in the coming weeks!

**Comment by jaredmcqueen** [comment]
nevermind, I think I got it.

```rust
let () = stream
    .map_err(Error::WebSocket)
    .try_for_each(|result| async {
        result
            .map(|data| {
                match data {
                    Data::Bar(_) => println!("got bar {:?}", data),
                    Data::Quote(_) => println!("got quote {:?}", data),
                    Data::Trade(_) => println!("got trade {:?}", data),
                    _ => println!("got other {:?}", data),
                };
            })
            .map_err(Error::Json)
    })
    .await
    .unwrap();

```

**Comment by jaredmcqueen** [comment]
closing, although I would still like to have better examples.  Perhaps a PR once I get more experience with this library.

**Comment by d-e-s-o** [comment]
Sounds good; glad you figured it out.
