### ISSUE TITLE
automatic websocket reconnection

### ISSUE THREAD

**Issue by jaredmcqueen** [d-e-s-o/apca#62]
ref discussion https://github.com/d-e-s-o/apca/discussions/61

would it be possible to request a feature for automatic websocket reconnection?

I think the error is from here: https://github.com/snapview/tungstenite-rs/blob/57d9e23939085c342949e62df799d75ed7c27d2f/src/protocol/mod.rs#L619

I'm still new~ish to rust so it may be entirely possible that I'm just using a bad design pattern to connect to Alpaca and keep the connection refreshed.  I easily get 10k+ quotes per second for a long stretches of time before my program crashes on the error in question.

**Comment by d-e-s-o** [comment]
I don't believe you can just reconnect. All the server-side state could be lost from what I understand.

**Comment by jaredmcqueen** [comment]
ok, i was thinking that reconnecting would resume the websocket flow.  I believe the Go library may do this but it's been a while

**Comment by jaredmcqueen** [comment]
closing.  Will just re-connect, re-subscribe, and retry flow on TCP errors.
