### ISSUE TITLE
 Implementing Options Trading for Beta Users in Alpaca's Paper Environment

### ISSUE THREAD

**Issue by matiasvillaverde** [d-e-s-o/apca#76]
Alpaca has recently introduced support for options trading for selected beta users in its paper trading environment. 

As a new Rust developer, I'm interested in exploring how I could contribute to expanding this feature. Although relatively new to this language, I am eager to apply my growing skills to real-world practices, while also learning from more experienced developers.

I am looking forward to any guidance or suggestions the community can offer.

**Comment by d-e-s-o** [comment]
Where is the documentation for options @matiasvillaverde? Haven't found any traces of anything.

**Comment by JMANN240** [comment]
@d-e-s-o I have a fork where I implemented [options chain](https://docs.alpaca.markets/reference/optionchain) functionality. Any chance that could be merged in? I can make a PR.

**Comment by d-e-s-o** [comment]
No, sorry. I can't afford to spend any more time on wrapping an API maintained by monkeys without any idea of what software versioning or backwards compatibility means (or software quality for that matter).

**Comment by JMANN240** [comment]
Yeah, I don't blame you. Understood.
